name = "FastBroadcast"
uuid = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
authors = ["Yingbo Ma <mayingbo5@gmail.com> and Chris Elrod <elrodc@gmail.com>"]
version = "0.1.11"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
Polyester = "0.5, 0.6"
Static = "0.3, 0.4"
julia = "1.5"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
PerformanceTestTools = "dc46b164-d16f-48ec-a853-60448fc869fe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "MuladdMacro", "PerformanceTestTools", "SparseArrays", "Test"]
